language: node_js
node_js:
  - 14
env:
  - CXX=g++-5 NODE_ENV=test
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
